# Generated by Django 6.0.2 on 2026-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Work location', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('gardening', 'Gardening'), ('moving', 'Moving'), ('ac', 'AC Technician'), ('appliance', 'Appliance Repair'), ('other', 'Other')], max_length=50),
        ),
    ]
