# Generated by Django 6.0.2 on 2026-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workerprofile_location_alter_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='exact_location',
            field=models.TextField(default='', help_text='Exact address/location for the job'),
        ),
    ]
