# Generated by Django 6.0.2 on 2026-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_job_description_job_exact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the job', null=True, upload_to='job_images/'),
        ),
    ]
