# Generated by Django 6.0.2 on 2026-03-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_received', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='accounts.job')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='accounts.quotation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quotation', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('offer', 'Initial Offer'), ('counter', 'Counter Offer'), ('accept', 'Accepted'), ('reject', 'Rejected'), ('text', 'Message')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.negotiation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
