# Generated by Django 5.2.13 on 2026-04-19 13:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_alter_availability_id_alter_favorite_id_alter_job_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="offered_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Emergency contact must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price per job",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="experience",
            field=models.IntegerField(
                help_text="Years of experience",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
